
SELECT * FROM PLAYLIST
USE Spotitube

INSERT INTO [USER] VALUES ('Lars', '314156yhrsfad-a', '909090')
INSERT INTO [USER] VALUES ('Test', '1312214-ADOIJWNF-23', '12345678')

INSERT INTO PLAYLIST VALUES('Lars', 'Death Metal') 
INSERT INTO PLAYLIST VALUES('Test', 'Pop')

INSERT INTO TRACK (TRACK_ID, TITLE, PERFORMER, DURATION, ALBUM)
VALUES (1, 'Song for Someone', 'The Frames', 350, 'The cost')

INSERT INTO TRACK (TRACK_ID, TITLE, PERFORMER, DURATION, PLAYCOUNT, PUBLICATIONDATE, DESCRIPTION)
VALUES (2, 'The Cost', 'The frames', 423, 37, '10-01-2005', 'Title song from the Album The Cost')

INSERT INTO TRACK_IN_PLAYLIST
VALUES(1,1,1),(2,1,0)
USE master